const home = {
  table: [
    {
      id: '1',
      'PO Number': 'A11570K',
      'Original Material Name': 'Conventional Cotton',
      'Responsible Material': 'Better Cotton',
      'Material Group': 'Cotton',
      'PO Material Weight (t)': ' 0.09677 ',
      'Responsible Transaction Weight (t)': ' -   ',
      Status: 'Awaiting Evidence',
      'Evidence Reference': 'null',
      Mill: 'null',
      Factory: 'null',
      Sender: 'null',
      'Product Type': 'null',
      'Conversion Factor': 'null',
    },
    {
      id: '2',
      'PO Number': 'A30086K',
      'Original Material Name': 'Conventional Cotton',
      'Responsible Material': 'Better Cotton',
      'Material Group': 'Cotton',
      'PO Material Weight (t)': ' 0.12530 ',
      'Responsible Transaction Weight (t)': ' -   ',
      Status: 'Awaiting Evidence',
      'Evidence Reference': 'null',
      Mill: 'null',
      Factory: 'null',
      Sender: 'null',
      'Product Type': 'null',
      'Conversion Factor': 'null',
    },
    {
      id: '3',
      'PO Number': 'A71283K',
      'Original Material Name': 'Conventional Cotton',
      'Responsible Material': 'Better Cotton',
      'Material Group': 'Cotton',
      'PO Material Weight (t)': ' 0.11910 ',
      'Responsible Transaction Weight (t)': ' -   ',
      Status: 'Awaiting Evidence',
      'Evidence Reference': 'null',
      Mill: 'null',
      Factory: 'null',
      Sender: 'null',
      'Product Type': 'null',
      'Conversion Factor': 'null',
    },
    {
      id: '4',
      'PO Number': 'A85612K',
      'Original Material Name': 'Conventional Cotton',
      'Responsible Material': 'Better Cotton',
      'Material Group': 'Cotton',
      'PO Material Weight (t)': ' 0.12654 ',
      'Responsible Transaction Weight (t)': ' -   ',
      Status: 'Awaiting Evidence',
      'Evidence Reference': 'null',
      Mill: 'null',
      Factory: 'null',
      Sender: 'null',
      'Product Type': 'null',
      'Conversion Factor': 'null',
    },
    {
      id: '5',
      'PO Number': 'B52833K',
      'Original Material Name': 'Conventional Cotton',
      'Responsible Material': 'Better Cotton',
      'Material Group': 'Cotton',
      'PO Material Weight (t)': ' 0.11165 ',
      'Responsible Transaction Weight (t)': ' -   ',
      Status: 'Awaiting Evidence',
      'Evidence Reference': 'null',
      Mill: 'null',
      Factory: 'null',
      Sender: 'null',
      'Product Type': 'null',
      'Conversion Factor': 'null',
    },
    {
      id: '6',
      'PO Number': 'B59363K',
      'Original Material Name': 'Conventional Cotton',
      'Responsible Material': 'Better Cotton',
      'Material Group': 'Cotton',
      'PO Material Weight (t)': ' 0.09304 ',
      'Responsible Transaction Weight (t)': ' -   ',
      Status: 'Awaiting Evidence',
      'Evidence Reference': 'null',
      Mill: 'null',
      Factory: 'null',
      Sender: 'null',
      'Product Type': 'null',
      'Conversion Factor': 'null',
    },
    {
      id: '7',
      'PO Number': 'B97344K',
      'Original Material Name': 'Conventional Cotton',
      'Responsible Material': 'Better Cotton',
      'Material Group': 'Cotton',
      'PO Material Weight (t)': ' 0.13647 ',
      'Responsible Transaction Weight (t)': ' -   ',
      Status: 'Awaiting Evidence',
      'Evidence Reference': 'null',
      Mill: 'null',
      Factory: 'null',
      Sender: 'null',
      'Product Type': 'null',
      'Conversion Factor': 'null',
    },
    {
      id: '8',
      'PO Number': 'C21502K',
      'Original Material Name': 'Conventional Cotton',
      'Responsible Material': 'Better Cotton',
      'Material Group': 'Cotton',
      'PO Material Weight (t)': ' 0.14515 ',
      'Responsible Transaction Weight (t)': ' -   ',
      Status: 'Awaiting Evidence',
      'Evidence Reference': 'null',
      Mill: 'null',
      Factory: 'null',
      Sender: 'null',
      'Product Type': 'null',
      'Conversion Factor': 'null',
    },
    {
      id: '9',
      'PO Number': 'C28260K',
      'Original Material Name': 'Conventional Cotton',
      'Responsible Material': 'Better Cotton',
      'Material Group': 'Cotton',
      'PO Material Weight (t)': ' 0.09429 ',
      'Responsible Transaction Weight (t)': ' -   ',
      Status: 'Awaiting Evidence',
      'Evidence Reference': 'null',
      Mill: 'null',
      Factory: 'null',
      Sender: 'null',
      'Product Type': 'null',
      'Conversion Factor': 'null',
    },
    {
      id: '10',
      'PO Number': 'C51935K',
      'Original Material Name': 'Conventional Cotton',
      'Responsible Material': 'Better Cotton',
      'Material Group': 'Cotton',
      'PO Material Weight (t)': ' 0.11413 ',
      'Responsible Transaction Weight (t)': ' -   ',
      Status: 'Awaiting Evidence',
      'Evidence Reference': 'null',
      Mill: 'null',
      Factory: 'null',
      Sender: 'null',
      'Product Type': 'null',
      'Conversion Factor': 'null',
    },
  ],
  departments: [
    {
      title: 'Department 1',
      value: 78,
    },
    {
      title: 'Department 2',
      value: 69,
    },
    {
      title: 'Department 3',
      value: 51,
    },
    {
      title: 'Department 4',
      value: 46,
    },
    {
      title: 'Department 5',
      value: 34,
    },
    {
      title: 'Department 6',
      value: 27,
    },
    {
      title: 'Department 7',
      value: 20,
    },
    {
      title: 'Department 8',
      value: 14,
    },
  ],
  suppliers: [
    {
      title: 'Supplier 1',
      value: 78,
    },
    {
      title: 'Supplier 2',
      value: 69,
    },
    {
      title: 'Supplier 3',
      value: 51,
    },
    {
      title: 'Supplier 4',
      value: 46,
    },
    {
      title: 'Supplier 5',
      value: 34,
    },
    {
      title: 'Supplier 6',
      value: 27,
    },
    {
      title: 'Supplier 7',
      value: 20,
    },
    {
      title: 'Supplier 8',
      value: 14,
    },
  ],
};

const materialReview = {
  kpi1: {
    'Responsibly Sourced': 55,
    Conventional: 45,
  },
  kpi2: {
    'Better Cotton': 55,
    'Organic Cotton': 27,
    'Recycled Cotton': 18,
  },
  kpi3: [
    {
      department: 'Department 1',
      materials: {
        Conventional: 2,
        Recycled: 3,
        Organic: 1,
        'Better Cotton': 2,
      },
    },
    {
      department: 'Department 2',
      materials: {
        Conventional: 4,
        Recycled: 3,
        Organic: 1,
        'Better Cotton': 2,
      },
    },
    {
      department: 'Department 3',
      materials: {
        Conventional: 1,
        Recycled: 2,
        Organic: 1,
        'Better Cotton': 3,
      },
    },
    {
      department: 'Department 4',
      materials: {
        Conventional: 1,
        Recycled: 0,
        Organic: 3,
        'Better Cotton': 4,
      },
    },
    {
      department: 'Department 5',
      materials: {
        Conventional: 25,
        Recycled: 2,
        Organic: 1,
        'Better Cotton': 4,
      },
    },
    {
      department: 'Department 6',
      materials: {
        Conventional: 2,
        Recycled: 5,
        Organic: 7,
        'Better Cotton': 1,
      },
    },
    {
      department: 'Department 7',
      materials: {
        Conventional: 4,
        Recycled: 4,
        Organic: 4,
        'Better Cotton': 1,
      },
    },
    {
      department: 'Department 8',
      materials: {
        Conventional: 3,
        Recycled: 2,
        Organic: 1,
        'Better Cotton': 2,
      },
    },
    {
      department: 'Department 9',
      materials: {
        Conventional: 3,
        Recycled: 2,
        Organic: 1,
        'Better Cotton': 3,
      },
    },
    {
      department: 'Department 10',
      materials: {
        Conventional: 1,
        Recycled: 1,
        Organic: 1,
        'Better Cotton': 1,
      },
    },
  ],
};

const supplierTableData = [
  {
    id: '0',
    'PO Supplier': 'Arktic Knits',
    'PO Factory': 'SAAB Co., Ltd.',
    'Factory Country': 'Norway',
    'PO Units': '113,67',
  },
  {
    id: '1',
    'PO Supplier': 'Arktic Knits',
    'PO Factory': 'SAAB Co., Ltd.',
    'Factory Country': 'Norway',
    'PO Units': '113,67',
  },
  {
    id: '2',
    'PO Supplier': 'Arktic Knits',
    'PO Factory': 'SAAB Co., Ltd.',
    'Factory Country': 'Norway',
    'PO Units': '113,67',
  },
  {
    id: '3',
    'PO Supplier': 'Arktic Knits',
    'PO Factory': 'SAAB Co., Ltd.',
    'Factory Country': 'Norway',
    'PO Units': '113,67',
  },
  {
    id: '4',
    'PO Supplier': 'Arktic Knits',
    'PO Factory': 'SAAB Co., Ltd.',
    'Factory Country': 'Norway',
    'PO Units': '113,67',
  },
  {
    id: '5',
    'PO Supplier': 'Arktic Knits',
    'PO Factory': 'SAAB Co., Ltd.',
    'Factory Country': 'Norway',
    'PO Units': '113,67',
  },
];

module.exports = {
  home,
  materialReview,
  supplierTableData,
};
